parameters:

services:
    cms.form.type.element:
        class: Mp\CmsBundle\Form\Type\CmsElement
        tags:
            - { name: form.type, alias: mp_cms_element }
            
    cms.form.type.image:
        class: Mp\CmsBundle\Form\Type\CmsImageType
        tags:
            - { name: form.type, alias: mp_cms_image }

    cms.form.type.text:
        class: Mp\CmsBundle\Form\Type\CmsText
        tags:
            - { name: form.type, alias: mp_cms_text }
    
    cms.form.type.image_text:
        class: Mp\CmsBundle\Form\Type\CmsImageTextType
        tags:
            - { name: form.type, alias: mp_cms_image_text }
        
    form.file.type.extension:
        class: Mp\CmsBundle\Form\Extension\FileTypeExtension
        tags:
            - { name: form.type_extension, alias: file }

            