<?php

namespace MediaparkLt\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class CmsImageGalleryRepository extends EntityRepository {

}
